/**
 * Marketing vocabulary bank shared by the dashboard's Vocabulary Coach
 * widget and the full Vocabulary Builder practice mode. One flat list so
 * both surfaces stay in sync — add terms here, they show up in both places.
 */

export type VocabLevel = 'beginner' | 'advanced'

export interface VocabTerm {
  id: string
  term: string
  definition: string
  category: string
  level: VocabLevel
}

export const vocabularyTerms: VocabTerm[] = [
  {
    id: 'cac',
    term: 'CAC (Customer Acquisition Cost)',
    definition: 'The total sales and marketing cost required to acquire one new customer.',
    category: 'Analytics',
    level: 'beginner',
  },
  {
    id: 'ltv',
    term: 'LTV (Customer Lifetime Value)',
    definition: 'The total revenue a business can expect from a single customer over the life of the relationship.',
    category: 'Analytics',
    level: 'advanced',
  },
  {
    id: 'ctr',
    term: 'CTR (Click-Through Rate)',
    definition: 'The percentage of people who click a link or ad after seeing it.',
    category: 'Analytics',
    level: 'beginner',
  },
  {
    id: 'cpc',
    term: 'CPC (Cost Per Click)',
    definition: 'The amount an advertiser pays each time someone clicks their ad.',
    category: 'Paid Media',
    level: 'beginner',
  },
  {
    id: 'cpm',
    term: 'CPM (Cost Per Mille)',
    definition: 'The cost of one thousand ad impressions, used to compare ad pricing across platforms.',
    category: 'Paid Media',
    level: 'advanced',
  },
  {
    id: 'roas',
    term: 'ROAS (Return on Ad Spend)',
    definition: 'The revenue generated for every unit of currency spent on advertising.',
    category: 'Analytics',
    level: 'advanced',
  },
  {
    id: 'attribution-window',
    term: 'Attribution Window',
    definition: 'The time period after someone interacts with an ad during which a resulting conversion is credited to it.',
    category: 'Analytics',
    level: 'advanced',
  },
  {
    id: 'bounce-rate',
    term: 'Bounce Rate',
    definition: 'The percentage of visitors who leave a site after viewing only one page.',
    category: 'Analytics',
    level: 'beginner',
  },
  {
    id: 'serp',
    term: 'SERP (Search Engine Results Page)',
    definition: 'The page a search engine displays in response to a user’s query.',
    category: 'SEO',
    level: 'advanced',
  },
  {
    id: 'backlink',
    term: 'Backlink',
    definition: 'A link from one website to a page on another site, used as a signal of authority and trust.',
    category: 'SEO',
    level: 'beginner',
  },
  {
    id: 'domain-authority',
    term: 'Domain Authority',
    definition: 'A score that predicts how well a website is likely to rank on search engine results pages.',
    category: 'SEO',
    level: 'advanced',
  },
  {
    id: 'organic-traffic',
    term: 'Organic Traffic',
    definition: 'Visitors who arrive at a website through unpaid search engine results.',
    category: 'SEO',
    level: 'advanced',
  },
  {
    id: 'long-tail-keyword',
    term: 'Long-Tail Keyword',
    definition: 'A longer, more specific search phrase that has lower search volume but often higher purchase intent.',
    category: 'SEO',
    level: 'advanced',
  },
  {
    id: 'ab-testing',
    term: 'A/B Testing',
    definition: 'Comparing two versions of a page, email, or ad to see which one performs better.',
    category: 'Optimization',
    level: 'beginner',
  },
  {
    id: 'conversion-funnel',
    term: 'Conversion Funnel',
    definition: 'The stages a prospect moves through on the way from first awareness to completing a purchase.',
    category: 'Strategy',
    level: 'beginner',
  },
  {
    id: 'retargeting',
    term: 'Retargeting',
    definition: 'Showing ads specifically to people who have already visited your site or app.',
    category: 'Paid Media',
    level: 'advanced',
  },
  {
    id: 'ugc',
    term: 'UGC (User-Generated Content)',
    definition: 'Content such as photos, reviews, or videos created by customers rather than the brand itself.',
    category: 'Content & Social',
    level: 'beginner',
  },
  {
    id: 'impressions',
    term: 'Impressions',
    definition: 'The number of times an ad or post is displayed, regardless of whether it was clicked.',
    category: 'Content & Social',
    level: 'beginner',
  },
  {
    id: 'reach',
    term: 'Reach',
    definition: 'The number of unique people who saw a piece of content.',
    category: 'Content & Social',
    level: 'beginner',
  },
  {
    id: 'engagement-rate',
    term: 'Engagement Rate',
    definition: 'Likes, comments, and shares divided by reach or followers, showing how actively an audience responds.',
    category: 'Content & Social',
    level: 'beginner',
  },
  {
    id: 'seo',
    term: 'SEO (Search Engine Optimization)',
    definition: 'The practice of improving a website so it ranks higher in unpaid search results.',
    category: 'SEO',
    level: 'beginner',
  },
  {
    id: 'sem',
    term: 'SEM (Search Engine Marketing)',
    definition: 'Paid tactics, such as search ads, used to increase a brand’s visibility in search results.',
    category: 'Paid Media',
    level: 'beginner',
  },
  {
    id: 'ppc',
    term: 'PPC (Pay-Per-Click)',
    definition: 'An advertising model where the advertiser pays a fee only when their ad is actually clicked.',
    category: 'Paid Media',
    level: 'beginner',
  },
  {
    id: 'kpi',
    term: 'KPI (Key Performance Indicator)',
    definition: 'A measurable value that shows how effectively a team is achieving a specific goal.',
    category: 'Strategy',
    level: 'beginner',
  },
  {
    id: 'conversion-rate',
    term: 'Conversion Rate',
    definition: 'The percentage of visitors who complete a desired action, such as a purchase or sign-up.',
    category: 'Analytics',
    level: 'beginner',
  },
  {
    id: 'lead-magnet',
    term: 'Lead Magnet',
    definition: 'A free resource, such as a guide or template, offered in exchange for a visitor’s contact details.',
    category: 'Strategy',
    level: 'advanced',
  },
  {
    id: 'drip-campaign',
    term: 'Drip Campaign',
    definition: 'A series of automated marketing emails sent on a set schedule or triggered by user behavior.',
    category: 'Email & CRM',
    level: 'advanced',
  },
  {
    id: 'segmentation',
    term: 'Segmentation',
    definition: 'Dividing an audience into smaller groups based on shared traits, such as behavior or demographics.',
    category: 'Strategy',
    level: 'advanced',
  },
  {
    id: 'churn-rate',
    term: 'Churn Rate',
    definition: 'The percentage of customers who stop using a product or service over a given period.',
    category: 'Analytics',
    level: 'advanced',
  },
  {
    id: 'brand-equity',
    term: 'Brand Equity',
    definition: 'The added value a brand name gives a product beyond its basic functional benefits.',
    category: 'Strategy',
    level: 'advanced',
  },
  {
    id: 'value-proposition',
    term: 'Value Proposition',
    definition: 'The clear reason a customer should choose your product over the available alternatives.',
    category: 'Strategy',
    level: 'advanced',
  },
  {
    id: 'impression-share',
    term: 'Impression Share',
    definition: 'The percentage of possible ad impressions an advertiser actually received out of the total available.',
    category: 'Paid Media',
    level: 'advanced',
  },
  {
    id: 'marketing',
    term: 'Marketing',
    definition: 'The set of activities a business uses to identify, attract, and retain customers by communicating value.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'market',
    term: 'Market',
    definition: 'The full group of potential and existing customers for a product or service.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'customer',
    term: 'Customer',
    definition: 'A person or organization that buys or uses a product or service.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'customer-need',
    term: 'Customer Need',
    definition: 'A basic requirement a customer must satisfy to survive or function, independent of any brand.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'customer-want',
    term: 'Customer Want',
    definition: 'The specific way a customer chooses to satisfy a need, shaped by preference and culture.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'customer-demand',
    term: 'Customer Demand',
    definition: 'A want backed by the ability and willingness to pay for it.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'usp',
    term: 'USP',
    definition: 'Unique Selling Proposition — the one specific benefit that sets a product apart from every competitor.',
    category: 'Marketing Fundamentals',
    level: 'advanced',
  },
  {
    id: 'brand',
    term: 'Brand',
    definition: 'The overall perception, reputation, and feeling people associate with a company or product.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'branding',
    term: 'Branding',
    definition: 'The ongoing process of shaping how a company is perceived through name, design, voice, and experience.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'brand-identity',
    term: 'Brand Identity',
    definition: 'The visible elements — logo, colors, typography, and tone — that make a brand recognizable.',
    category: 'Marketing Fundamentals',
    level: 'advanced',
  },
  {
    id: 'brand-positioning',
    term: 'Brand Positioning',
    definition: 'The specific place a brand occupies in a customer\'s mind relative to competitors.',
    category: 'Marketing Fundamentals',
    level: 'advanced',
  },
  {
    id: 'market-segmentation',
    term: 'Market Segmentation',
    definition: 'Dividing a broad market into smaller groups of customers who share similar needs or traits.',
    category: 'Marketing Fundamentals',
    level: 'advanced',
  },
  {
    id: 'target-audience',
    term: 'Target Audience',
    definition: 'The specific group of people a marketing campaign or product is designed to reach.',
    category: 'Marketing Fundamentals',
    level: 'advanced',
  },
  {
    id: 'buyer-persona',
    term: 'Buyer Persona',
    definition: 'A semi-fictional profile of an ideal customer, built from real data and research.',
    category: 'Marketing Fundamentals',
    level: 'advanced',
  },
  {
    id: 'marketing-mix-4ps',
    term: 'Marketing Mix (4Ps)',
    definition: 'The four controllable levers of marketing strategy: Product, Price, Place, and Promotion.',
    category: 'Marketing Fundamentals',
    level: 'advanced',
  },
  {
    id: 'product',
    term: 'Product',
    definition: 'The good, service, or solution a business offers to meet a customer need.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'price',
    term: 'Price',
    definition: 'The amount a customer pays in exchange for a product or service.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'place',
    term: 'Place',
    definition: 'The channels and locations through which a product reaches the customer.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'promotion',
    term: 'Promotion',
    definition: 'The communication activities — ads, PR, offers — used to make customers aware of a product.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'customer-journey',
    term: 'Customer Journey',
    definition: 'The full path a person takes from first hearing about a brand to becoming a loyal customer.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'marketing-funnel',
    term: 'Marketing Funnel',
    definition: 'A model showing the stages customers pass through, from awareness to purchase and loyalty.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'b2b',
    term: 'B2B',
    definition: 'Business-to-Business — a company selling products or services to other businesses rather than individual consumers.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'b2c',
    term: 'B2C',
    definition: 'Business-to-Consumer — a company selling products or services directly to individual customers.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'c2c',
    term: 'C2C',
    definition: 'Consumer-to-Consumer — a model where individuals sell products or services directly to other individuals.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'value',
    term: 'Value',
    definition: 'The benefit a customer perceives from a product relative to what they pay for it.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'competition',
    term: 'Competition',
    definition: 'Other businesses offering similar products or services to the same target customers.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'competitive-advantage',
    term: 'Competitive Advantage',
    definition: 'A distinct edge — cost, quality, or innovation — that lets a business outperform its rivals.',
    category: 'Marketing Fundamentals',
    level: 'advanced',
  },
  {
    id: 'market-share',
    term: 'Market Share',
    definition: 'The percentage of total sales in a market captured by one specific company.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'customer-retention',
    term: 'Customer Retention',
    definition: 'The strategies and metrics used to keep existing customers buying instead of switching away.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'customer-acquisition',
    term: 'Customer Acquisition',
    definition: 'The process and cost of gaining a new paying customer.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'aida',
    term: 'AIDA',
    definition: 'A classic marketing framework describing the stages a buyer moves through: Attention, Interest, Desire, Action.',
    category: 'Marketing Fundamentals',
    level: 'advanced',
  },
  {
    id: 'marketing-strategy',
    term: 'Marketing Strategy',
    definition: 'The long-term plan defining which markets to pursue and how to win them.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'marketing-tactics',
    term: 'Marketing Tactics',
    definition: 'The specific, short-term actions used to execute a broader marketing strategy.',
    category: 'Marketing Fundamentals',
    level: 'beginner',
  },
  {
    id: 'market-research',
    term: 'Market Research',
    definition: 'The process of gathering and analyzing information about customers, competitors, and market conditions.',
    category: 'Market Research',
    level: 'beginner',
  },
  {
    id: 'primary-research',
    term: 'Primary Research',
    definition: 'Original data collected firsthand for a specific purpose, such as surveys or interviews.',
    category: 'Market Research',
    level: 'advanced',
  },
  {
    id: 'secondary-research',
    term: 'Secondary Research',
    definition: 'Analysis of existing data and reports that someone else already collected.',
    category: 'Market Research',
    level: 'advanced',
  },
  {
    id: 'quantitative-research',
    term: 'Quantitative Research',
    definition: 'Research that gathers numerical data to measure patterns and test hypotheses statistically.',
    category: 'Market Research',
    level: 'advanced',
  },
  {
    id: 'qualitative-research',
    term: 'Qualitative Research',
    definition: 'Research that explores opinions, motivations, and behavior through open-ended, non-numerical methods.',
    category: 'Market Research',
    level: 'advanced',
  },
  {
    id: 'surveys',
    term: 'Surveys',
    definition: 'A structured set of questions used to collect data from a large group of people.',
    category: 'Market Research',
    level: 'beginner',
  },
  {
    id: 'focus-groups',
    term: 'Focus Groups',
    definition: 'A small, guided discussion with a group of target customers to gather in-depth feedback.',
    category: 'Market Research',
    level: 'beginner',
  },
  {
    id: 'interviews',
    term: 'Interviews',
    definition: 'One-on-one conversations used to gather detailed, personal insight from a research participant.',
    category: 'Market Research',
    level: 'beginner',
  },
  {
    id: 'observation',
    term: 'Observation',
    definition: 'Watching how customers actually behave in real settings, rather than asking them directly.',
    category: 'Market Research',
    level: 'beginner',
  },
  {
    id: 'competitor-analysis',
    term: 'Competitor Analysis',
    definition: 'Systematically evaluating rival businesses\' strategy, strengths, and weaknesses to inform your own.',
    category: 'Market Research',
    level: 'advanced',
  },
  {
    id: 'swot',
    term: 'SWOT',
    definition: 'A framework for evaluating a business\'s Strengths, Weaknesses, Opportunities, and Threats.',
    category: 'Market Research',
    level: 'advanced',
  },
  {
    id: 'pestle',
    term: 'PESTLE',
    definition: 'A framework analyzing the Political, Economic, Social, Technological, Legal, and Environmental factors affecting a business.',
    category: 'Market Research',
    level: 'advanced',
  },
  {
    id: 'tam',
    term: 'TAM',
    definition: 'Total Addressable Market — the total revenue opportunity if a product captured 100% of its market.',
    category: 'Market Research',
    level: 'advanced',
  },
  {
    id: 'sam',
    term: 'SAM',
    definition: 'Serviceable Addressable Market — the portion of the total market a business can realistically reach.',
    category: 'Market Research',
    level: 'advanced',
  },
  {
    id: 'som',
    term: 'SOM',
    definition: 'Serviceable Obtainable Market — the share of the reachable market a business can realistically capture.',
    category: 'Market Research',
    level: 'advanced',
  },
  {
    id: 'keyword-research',
    term: 'Keyword Research',
    definition: 'Finding and evaluating the search terms people use, to guide content and ad targeting.',
    category: 'Market Research',
    level: 'advanced',
  },
  {
    id: 'search-intent',
    term: 'Search Intent',
    definition: 'The underlying goal behind a search query — to learn, compare, or buy.',
    category: 'Market Research',
    level: 'beginner',
  },
  {
    id: 'customer-pain-points',
    term: 'Customer Pain Points',
    definition: 'The specific problems or frustrations a customer experiences that a product can solve.',
    category: 'Market Research',
    level: 'beginner',
  },
  {
    id: 'consumer-behaviour',
    term: 'Consumer Behaviour',
    definition: 'The study of how and why people decide to buy, use, and dispose of products.',
    category: 'Market Research',
    level: 'beginner',
  },
  {
    id: 'market-trends',
    term: 'Market Trends',
    definition: 'The general direction an industry or consumer behavior is moving over time.',
    category: 'Market Research',
    level: 'beginner',
  },
  {
    id: 'demand-analysis',
    term: 'Demand Analysis',
    definition: 'Evaluating how much of a product customers want at different prices and conditions.',
    category: 'Market Research',
    level: 'advanced',
  },
  {
    id: 'campaign',
    term: 'Campaign',
    definition: 'An organized set of ads with a shared goal, budget, and target audience.',
    category: 'Meta Ads',
    level: 'beginner',
  },
  {
    id: 'ad-set',
    term: 'Ad Set',
    definition: 'A Meta Ads grouping level where you define the audience, budget, and schedule for a set of ads.',
    category: 'Meta Ads',
    level: 'advanced',
  },
  {
    id: 'ad',
    term: 'Ad',
    definition: 'The actual creative — image, video, or text — shown to a person within a campaign.',
    category: 'Meta Ads',
    level: 'beginner',
  },
  {
    id: 'meta-pixel',
    term: 'Meta Pixel',
    definition: 'A tracking snippet placed on a website that reports visitor actions back to Meta for ad optimization.',
    category: 'Meta Ads',
    level: 'advanced',
  },
  {
    id: 'conversions-api',
    term: 'Conversions API',
    definition: 'A server-side connection that sends conversion data directly to Meta, bypassing browser tracking limits.',
    category: 'Meta Ads',
    level: 'advanced',
  },
  {
    id: 'campaign-objective',
    term: 'Campaign Objective',
    definition: 'The specific business goal — awareness, traffic, sales — a Meta Ads campaign is optimized for.',
    category: 'Meta Ads',
    level: 'advanced',
  },
  {
    id: 'advantage-plus',
    term: 'Advantage+',
    definition: 'Meta\'s automated ad system that uses AI to handle targeting, placements, and creative optimization.',
    category: 'Meta Ads',
    level: 'advanced',
  },
  {
    id: 'audience',
    term: 'Audience',
    definition: 'The group of people eligible to see a given ad, defined by targeting criteria.',
    category: 'Meta Ads',
    level: 'beginner',
  },
  {
    id: 'custom-audience',
    term: 'Custom Audience',
    definition: 'An audience built from a business\'s own data, like a customer list or website visitors.',
    category: 'Meta Ads',
    level: 'advanced',
  },
  {
    id: 'lookalike-audience',
    term: 'Lookalike Audience',
    definition: 'A new audience Meta builds by finding people who resemble an existing Custom Audience.',
    category: 'Meta Ads',
    level: 'advanced',
  },
  {
    id: 'cpa',
    term: 'CPA',
    definition: 'Cost Per Acquisition — the average amount spent to gain one customer or conversion.',
    category: 'Meta Ads',
    level: 'advanced',
  },
  {
    id: 'frequency',
    term: 'Frequency',
    definition: 'The average number of times a single person sees the same ad.',
    category: 'Meta Ads',
    level: 'advanced',
  },
  {
    id: 'learning-phase',
    term: 'Learning Phase',
    definition: 'The initial period after launching or editing an ad set while Meta\'s algorithm optimizes delivery.',
    category: 'Meta Ads',
    level: 'advanced',
  },
  {
    id: 'attribution',
    term: 'Attribution',
    definition: 'The practice of crediting a conversion to the specific ad or touchpoint that influenced it.',
    category: 'Meta Ads',
    level: 'advanced',
  },
  {
    id: 'bid-strategy',
    term: 'Bid Strategy',
    definition: 'The rule that tells an ad platform how to spend your budget to hit a goal.',
    category: 'Meta Ads',
    level: 'advanced',
  },
  {
    id: 'creative',
    term: 'Creative',
    definition: 'The actual visual and copy content of an ad — the image, video, and text.',
    category: 'Meta Ads',
    level: 'beginner',
  },
  {
    id: 'placement',
    term: 'Placement',
    definition: 'The specific location, like Feed or Stories, where an ad is shown.',
    category: 'Meta Ads',
    level: 'beginner',
  },
  {
    id: 'carousel-ads',
    term: 'Carousel Ads',
    definition: 'An ad format showing multiple images or videos a viewer can swipe through in one ad.',
    category: 'Meta Ads',
    level: 'advanced',
  },
  {
    id: 'lead-ads',
    term: 'Lead Ads',
    definition: 'An ad format with a built-in form that lets people submit contact details without leaving the app.',
    category: 'Meta Ads',
    level: 'advanced',
  },
  {
    id: 'instant-forms',
    term: 'Instant Forms',
    definition: 'The pre-filled, mobile-friendly forms used in Meta Lead Ads to reduce signup friction.',
    category: 'Meta Ads',
    level: 'advanced',
  },
  {
    id: 'search-campaign',
    term: 'Search Campaign',
    definition: 'A Google Ads campaign showing text ads to people actively searching for related terms.',
    category: 'Google Ads',
    level: 'beginner',
  },
  {
    id: 'display-campaign',
    term: 'Display Campaign',
    definition: 'A Google Ads campaign showing visual banner ads across a network of partner websites and apps.',
    category: 'Google Ads',
    level: 'beginner',
  },
  {
    id: 'performance-max',
    term: 'Performance Max',
    definition: 'A Google Ads campaign type that uses automation to serve ads across all Google channels from one campaign.',
    category: 'Google Ads',
    level: 'advanced',
  },
  {
    id: 'shopping-ads',
    term: 'Shopping Ads',
    definition: 'Product-based ads showing an image, price, and store name directly in Google search results.',
    category: 'Google Ads',
    level: 'advanced',
  },
  {
    id: 'quality-score',
    term: 'Quality Score',
    definition: 'Google\'s 1–10 rating of an ad\'s relevance, expected click-through rate, and landing page experience.',
    category: 'Google Ads',
    level: 'advanced',
  },
  {
    id: 'ad-rank',
    term: 'Ad Rank',
    definition: 'The value Google uses to decide an ad\'s position, based on bid and Quality Score.',
    category: 'Google Ads',
    level: 'advanced',
  },
  {
    id: 'keywords',
    term: 'Keywords',
    definition: 'The words or phrases advertisers bid on to trigger their ads in search results.',
    category: 'Google Ads',
    level: 'beginner',
  },
  {
    id: 'broad-match',
    term: 'Broad Match',
    definition: 'A keyword setting that shows ads for searches broadly related to the keyword, including synonyms.',
    category: 'Google Ads',
    level: 'advanced',
  },
  {
    id: 'phrase-match',
    term: 'Phrase Match',
    definition: 'A keyword setting that shows ads for searches containing the exact phrase, in order.',
    category: 'Google Ads',
    level: 'advanced',
  },
  {
    id: 'exact-match',
    term: 'Exact Match',
    definition: 'A keyword setting that shows ads only for searches matching the exact keyword or a close variant.',
    category: 'Google Ads',
    level: 'advanced',
  },
  {
    id: 'negative-keywords',
    term: 'Negative Keywords',
    definition: 'Search terms an advertiser excludes so their ads don\'t show for irrelevant queries.',
    category: 'Google Ads',
    level: 'advanced',
  },
  {
    id: 'maximize-conversions',
    term: 'Maximize Conversions',
    definition: 'An automated bidding strategy that spends a budget to get as many conversions as possible.',
    category: 'Google Ads',
    level: 'advanced',
  },
  {
    id: 'target-cpa',
    term: 'Target CPA',
    definition: 'An automated bidding strategy that aims to get conversions at or below a set cost per acquisition.',
    category: 'Google Ads',
    level: 'advanced',
  },
  {
    id: 'target-roas',
    term: 'Target ROAS',
    definition: 'An automated bidding strategy that aims to hit a specific return on ad spend.',
    category: 'Google Ads',
    level: 'advanced',
  },
  {
    id: 'search-impression-share',
    term: 'Search Impression Share',
    definition: 'The percentage of eligible search impressions an ad actually received.',
    category: 'Google Ads',
    level: 'advanced',
  },
  {
    id: 'ad-extensions',
    term: 'Ad Extensions',
    definition: 'Extra information — like links, phone numbers, or location — added to a search ad to boost visibility.',
    category: 'Google Ads',
    level: 'advanced',
  },
  {
    id: 'landing-page',
    term: 'Landing Page',
    definition: 'The webpage a visitor lands on after clicking an ad, designed to drive a specific action.',
    category: 'Google Ads',
    level: 'beginner',
  },
  {
    id: 'aeo',
    term: 'AEO',
    definition: 'Answer Engine Optimization — optimizing content to be directly surfaced as answers by AI and voice assistants.',
    category: 'SEO & AEO',
    level: 'beginner',
  },
  {
    id: 'meta-title',
    term: 'Meta Title',
    definition: 'The clickable headline of a page shown in search results, set in the page\'s HTML.',
    category: 'SEO & AEO',
    level: 'beginner',
  },
  {
    id: 'meta-description',
    term: 'Meta Description',
    definition: 'The short summary shown under a page\'s title in search results, meant to earn the click.',
    category: 'SEO & AEO',
    level: 'beginner',
  },
  {
    id: 'heading-tags',
    term: 'Heading Tags',
    definition: 'HTML tags (H1, H2, etc.) that structure a page\'s content and signal importance to search engines.',
    category: 'SEO & AEO',
    level: 'advanced',
  },
  {
    id: 'technical-seo',
    term: 'Technical SEO',
    definition: 'Optimizing a website\'s backend — speed, crawlability, structure — so search engines can find and rank it.',
    category: 'SEO & AEO',
    level: 'advanced',
  },
  {
    id: 'crawl',
    term: 'Crawl',
    definition: 'The process by which a search engine\'s bots discover and read pages across the web.',
    category: 'SEO & AEO',
    level: 'advanced',
  },
  {
    id: 'indexing',
    term: 'Indexing',
    definition: 'Storing a crawled page in a search engine\'s database so it can appear in results.',
    category: 'SEO & AEO',
    level: 'advanced',
  },
  {
    id: 'canonical-tag',
    term: 'Canonical Tag',
    definition: 'An HTML tag that tells search engines which version of a duplicate page is the master copy.',
    category: 'SEO & AEO',
    level: 'advanced',
  },
  {
    id: 'schema-markup',
    term: 'Schema Markup',
    definition: 'Structured code added to a page so search engines can display richer results, like star ratings.',
    category: 'SEO & AEO',
    level: 'advanced',
  },
  {
    id: 'core-web-vitals',
    term: 'Core Web Vitals',
    definition: 'Google\'s metrics for a page\'s loading speed, interactivity, and visual stability.',
    category: 'SEO & AEO',
    level: 'advanced',
  },
  {
    id: 'featured-snippet',
    term: 'Featured Snippet',
    definition: 'A highlighted answer box shown at the top of Google\'s search results, pulled from a ranking page.',
    category: 'SEO & AEO',
    level: 'advanced',
  },
  {
    id: 'internal-linking',
    term: 'Internal Linking',
    definition: 'Links connecting one page on a site to another, helping visitors and search engines navigate it.',
    category: 'SEO & AEO',
    level: 'advanced',
  },
  {
    id: 'external-linking',
    term: 'External Linking',
    definition: 'Links from a page pointing out to other websites.',
    category: 'SEO & AEO',
    level: 'advanced',
  },
  {
    id: 'page-authority',
    term: 'Page Authority',
    definition: 'A score predicting how well a specific page is likely to rank in search results.',
    category: 'SEO & AEO',
    level: 'advanced',
  },
  {
    id: 'google-analytics',
    term: 'Google Analytics',
    definition: 'Google\'s free platform for tracking and reporting website and app traffic and user behavior.',
    category: 'Analytics',
    level: 'beginner',
  },
  {
    id: 'ga4',
    term: 'GA4',
    definition: 'Google Analytics 4 — Google\'s current analytics platform, built around events rather than pageviews.',
    category: 'Analytics',
    level: 'beginner',
  },
  {
    id: 'event',
    term: 'Event',
    definition: 'A specific user action, like a click or video play, tracked as a data point in analytics.',
    category: 'Analytics',
    level: 'beginner',
  },
  {
    id: 'conversion',
    term: 'Conversion',
    definition: 'A completed action that counts as a success, such as a purchase or signup.',
    category: 'Analytics',
    level: 'beginner',
  },
  {
    id: 'session',
    term: 'Session',
    definition: 'A group of user interactions on a site or app within a given time frame.',
    category: 'Analytics',
    level: 'advanced',
  },
  {
    id: 'user',
    term: 'User',
    definition: 'A unique individual visiting a website or app, tracked across one or more sessions.',
    category: 'Analytics',
    level: 'advanced',
  },
  {
    id: 'utm',
    term: 'UTM',
    definition: 'Tags added to a URL that identify the source, medium, and campaign driving traffic to it.',
    category: 'Analytics',
    level: 'advanced',
  },
  {
    id: 'source',
    term: 'Source',
    definition: 'Where traffic originated from, such as Google, Facebook, or a specific website.',
    category: 'Analytics',
    level: 'advanced',
  },
  {
    id: 'medium',
    term: 'Medium',
    definition: 'The general category of a traffic source, such as organic, paid, email, or social.',
    category: 'Analytics',
    level: 'advanced',
  },
  {
    id: 'dimensions',
    term: 'Dimensions',
    definition: 'Descriptive attributes of your data in analytics, like browser, country, or page title.',
    category: 'Analytics',
    level: 'advanced',
  },
  {
    id: 'metrics',
    term: 'Metrics',
    definition: 'The quantitative measurements in analytics, like sessions, clicks, or revenue.',
    category: 'Analytics',
    level: 'advanced',
  },
  {
    id: 'funnel-analysis',
    term: 'Funnel Analysis',
    definition: 'Tracking where users drop off across the sequential steps toward a conversion.',
    category: 'Analytics',
    level: 'advanced',
  },
  {
    id: 'cohort-analysis',
    term: 'Cohort Analysis',
    definition: 'Comparing groups of users who share a starting point in time to see how their behavior evolves.',
    category: 'Analytics',
    level: 'advanced',
  },
  {
    id: 'dashboard',
    term: 'Dashboard',
    definition: 'A visual summary screen bringing together a business\'s key metrics in one place.',
    category: 'Analytics',
    level: 'advanced',
  },
  {
    id: 'looker-studio',
    term: 'Looker Studio',
    definition: 'Google\'s free tool for turning raw data into interactive, shareable reports and dashboards.',
    category: 'Analytics',
    level: 'advanced',
  },
  {
    id: 'bigquery',
    term: 'BigQuery',
    definition: 'Google\'s cloud data warehouse used to store and analyze very large marketing and analytics datasets.',
    category: 'Analytics',
    level: 'advanced',
  },
  {
    id: 'content-marketing',
    term: 'Content Marketing',
    definition: 'Creating and sharing valuable content to attract and retain a clearly defined audience.',
    category: 'Content Marketing',
    level: 'beginner',
  },
  {
    id: 'content-strategy',
    term: 'Content Strategy',
    definition: 'The plan guiding what content to create, for whom, and why, in service of business goals.',
    category: 'Content Marketing',
    level: 'advanced',
  },
  {
    id: 'content-calendar',
    term: 'Content Calendar',
    definition: 'A schedule that plans out what content will be published, where, and when.',
    category: 'Content Marketing',
    level: 'advanced',
  },
  {
    id: 'blog',
    term: 'Blog',
    definition: 'A regularly updated website section publishing articles, often used to drive organic traffic and build authority.',
    category: 'Content Marketing',
    level: 'beginner',
  },
  {
    id: 'copywriting',
    term: 'Copywriting',
    definition: 'Writing persuasive text designed to get a reader to take a specific action.',
    category: 'Content Marketing',
    level: 'beginner',
  },
  {
    id: 'cta',
    term: 'CTA',
    definition: 'Call To Action — the instruction, like \'Buy Now\' or \'Sign Up\', prompting a reader to act.',
    category: 'Content Marketing',
    level: 'beginner',
  },
  {
    id: 'hook',
    term: 'Hook',
    definition: 'The opening line or moment of a piece of content designed to grab attention immediately.',
    category: 'Content Marketing',
    level: 'beginner',
  },
  {
    id: 'storytelling',
    term: 'Storytelling',
    definition: 'Using narrative structure to make a brand\'s message more memorable and emotionally engaging.',
    category: 'Content Marketing',
    level: 'beginner',
  },
  {
    id: 'evergreen-content',
    term: 'Evergreen Content',
    definition: 'Content that stays relevant and valuable to readers long after it\'s published.',
    category: 'Content Marketing',
    level: 'advanced',
  },
  {
    id: 'email-marketing',
    term: 'Email Marketing',
    definition: 'Sending targeted messages directly to a subscriber\'s inbox to inform, nurture, or sell.',
    category: 'Content Marketing',
    level: 'beginner',
  },
  {
    id: 'newsletter',
    term: 'Newsletter',
    definition: 'A regularly sent email update sharing news, content, or offers with subscribers.',
    category: 'Content Marketing',
    level: 'beginner',
  },
  {
    id: 'engagement',
    term: 'Engagement',
    definition: 'How actively an audience interacts with content — likes, comments, shares, and time spent.',
    category: 'Content Marketing',
    level: 'advanced',
  },
  {
    id: 'content-funnel',
    term: 'Content Funnel',
    definition: 'Mapping different types of content to each stage of the buyer\'s journey.',
    category: 'Content Marketing',
    level: 'advanced',
  },
  {
    id: 'repurposing',
    term: 'Repurposing',
    definition: 'Reworking one piece of content into different formats to reach more people with less effort.',
    category: 'Content Marketing',
    level: 'advanced',
  },
  {
    id: 'topic-cluster',
    term: 'Topic Cluster',
    definition: 'A core \'pillar\' page linked to related subtopic pages, used to build SEO authority around a theme.',
    category: 'Content Marketing',
    level: 'advanced',
  },
  {
    id: 'marketing-automation',
    term: 'Marketing Automation',
    definition: 'Using software to automatically run repetitive marketing tasks like emails, ads, and follow-ups.',
    category: 'Marketing Automation & AI',
    level: 'beginner',
  },
  {
    id: 'crm',
    term: 'CRM',
    definition: 'Customer Relationship Management — software that tracks and manages a business\'s interactions with customers and leads.',
    category: 'Marketing Automation & AI',
    level: 'advanced',
  },
  {
    id: 'workflow',
    term: 'Workflow',
    definition: 'An automated sequence of steps triggered by a specific customer action or condition.',
    category: 'Marketing Automation & AI',
    level: 'advanced',
  },
  {
    id: 'trigger',
    term: 'Trigger',
    definition: 'The specific event, like a signup or abandoned cart, that starts an automated workflow.',
    category: 'Marketing Automation & AI',
    level: 'advanced',
  },
  {
    id: 'lead-scoring',
    term: 'Lead Scoring',
    definition: 'Ranking leads by assigning points based on their behavior and fit, to prioritize follow-up.',
    category: 'Marketing Automation & AI',
    level: 'advanced',
  },
  {
    id: 'chatbot',
    term: 'Chatbot',
    definition: 'An automated messaging tool that answers questions or guides users without a live person.',
    category: 'Marketing Automation & AI',
    level: 'beginner',
  },
  {
    id: 'email-sequence',
    term: 'Email Sequence',
    definition: 'A pre-written series of emails sent automatically over time to nurture a lead or customer.',
    category: 'Marketing Automation & AI',
    level: 'advanced',
  },
  {
    id: 'zapier',
    term: 'Zapier',
    definition: 'A no-code tool that connects different apps so actions in one automatically trigger actions in another.',
    category: 'Marketing Automation & AI',
    level: 'advanced',
  },
  {
    id: 'make',
    term: 'Make',
    definition: 'A visual automation platform for building multi-step workflows that connect apps and data.',
    category: 'Marketing Automation & AI',
    level: 'advanced',
  },
  {
    id: 'ai-prompt',
    term: 'AI Prompt',
    definition: 'The instruction given to an AI tool to generate a specific response or piece of content.',
    category: 'Marketing Automation & AI',
    level: 'advanced',
  },
  {
    id: 'prompt-engineering',
    term: 'Prompt Engineering',
    definition: 'The practice of crafting inputs to get more accurate and useful output from an AI model.',
    category: 'Marketing Automation & AI',
    level: 'advanced',
  },
  {
    id: 'llm',
    term: 'LLM',
    definition: 'Large Language Model — the type of AI model, like GPT, trained to understand and generate human language.',
    category: 'Marketing Automation & AI',
    level: 'advanced',
  },
  {
    id: 'ai-agent',
    term: 'AI Agent',
    definition: 'An AI system that can take multi-step actions toward a goal, not just answer questions.',
    category: 'Marketing Automation & AI',
    level: 'advanced',
  },
  {
    id: 'personalization',
    term: 'Personalization',
    definition: 'Tailoring content, offers, or experiences to an individual based on their data and behavior.',
    category: 'Marketing Automation & AI',
    level: 'advanced',
  },
  {
    id: 'predictive-analytics',
    term: 'Predictive Analytics',
    definition: 'Using historical data and statistical models to forecast future customer behavior or outcomes.',
    category: 'Marketing Automation & AI',
    level: 'advanced',
  },
  {
    id: 'a-b-testing-automation',
    term: 'A/B Testing Automation',
    definition: 'Using software to automatically split traffic between versions and route it to the winner.',
    category: 'Marketing Automation & AI',
    level: 'advanced',
  },
  {
    id: 'whatsapp-automation',
    term: 'WhatsApp Automation',
    definition: 'Using automated messages and chatbots to communicate with customers over WhatsApp at scale.',
    category: 'Marketing Automation & AI',
    level: 'advanced',
  },
  {
    id: 'api',
    term: 'API',
    definition: 'Application Programming Interface — a defined way for two pieces of software to exchange data.',
    category: 'Marketing Automation & AI',
    level: 'advanced',
  },
  {
    id: 'webhook',
    term: 'Webhook',
    definition: 'An automated message one system sends to another the instant a specific event happens.',
    category: 'Marketing Automation & AI',
    level: 'advanced',
  },
]
