/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as BecomeAPartnerInstitutionRouteImport } from './routes/become-a-partner-institution'
import { Route as BecomeAMentorRouteImport } from './routes/become-a-mentor'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromptLibraryIndexRouteImport } from './routes/prompt-library/index'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PromptLibraryLibraryIdRouteImport } from './routes/prompt-library/$libraryId'
import { Route as PartnershipsLoginRouteImport } from './routes/partnerships/login'
import { Route as PartnershipsLayoutRouteImport } from './routes/partnerships/_layout'
import { Route as CommunityMentorsRouteImport } from './routes/community/mentors'
import { Route as CommunityInstitutionsRouteImport } from './routes/community/institutions'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as AdminCertificatesRouteImport } from './routes/admin/certificates'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminAssessmentQuestionsRouteImport } from './routes/admin/assessment-questions'
import { Route as AdminAdsRouteImport } from './routes/admin/ads'
import { Route as PartnershipsLayoutIndexRouteImport } from './routes/partnerships/_layout/index'
import { Route as PartnershipsLayoutMentorsRouteImport } from './routes/partnerships/_layout/mentors'
import { Route as PartnershipsLayoutInstitutionPartnersRouteImport } from './routes/partnerships/_layout/institution-partners'
import { Route as PartnershipsLayoutDemoRequestsRouteImport } from './routes/partnerships/_layout/demo-requests'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAPartnerInstitutionRoute =
  BecomeAPartnerInstitutionRouteImport.update({
    id: '/become-a-partner-institution',
    path: '/become-a-partner-institution',
    getParentRoute: () => rootRouteImport,
  } as any)
const BecomeAMentorRoute = BecomeAMentorRouteImport.update({
  id: '/become-a-mentor',
  path: '/become-a-mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptLibraryIndexRoute = PromptLibraryIndexRouteImport.update({
  id: '/prompt-library/',
  path: '/prompt-library/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PromptLibraryLibraryIdRoute = PromptLibraryLibraryIdRouteImport.update({
  id: '/prompt-library/$libraryId',
  path: '/prompt-library/$libraryId',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsLoginRoute = PartnershipsLoginRouteImport.update({
  id: '/partnerships/login',
  path: '/partnerships/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsLayoutRoute = PartnershipsLayoutRouteImport.update({
  id: '/partnerships/_layout',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityMentorsRoute = CommunityMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityInstitutionsRoute = CommunityInstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => CommunityRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssessmentQuestionsRoute =
  AdminAssessmentQuestionsRouteImport.update({
    id: '/assessment-questions',
    path: '/assessment-questions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const PartnershipsLayoutIndexRoute = PartnershipsLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnershipsLayoutRoute,
} as any)
const PartnershipsLayoutMentorsRoute =
  PartnershipsLayoutMentorsRouteImport.update({
    id: '/mentors',
    path: '/mentors',
    getParentRoute: () => PartnershipsLayoutRoute,
  } as any)
const PartnershipsLayoutInstitutionPartnersRoute =
  PartnershipsLayoutInstitutionPartnersRouteImport.update({
    id: '/institution-partners',
    path: '/institution-partners',
    getParentRoute: () => PartnershipsLayoutRoute,
  } as any)
const PartnershipsLayoutDemoRequestsRoute =
  PartnershipsLayoutDemoRequestsRouteImport.update({
    id: '/demo-requests',
    path: '/demo-requests',
    getParentRoute: () => PartnershipsLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/become-a-mentor': typeof BecomeAMentorRoute
  '/become-a-partner-institution': typeof BecomeAPartnerInstitutionRoute
  '/certificate': typeof CertificateRoute
  '/community': typeof CommunityRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/games': typeof GamesRoute
  '/internships': typeof InternshipsRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/onboarding': typeof OnboardingRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tests': typeof TestsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/assessment-questions': typeof AdminAssessmentQuestionsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/community/institutions': typeof CommunityInstitutionsRoute
  '/community/mentors': typeof CommunityMentorsRoute
  '/partnerships': typeof PartnershipsLayoutRouteWithChildren
  '/partnerships/login': typeof PartnershipsLoginRoute
  '/prompt-library/$libraryId': typeof PromptLibraryLibraryIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/prompt-library/': typeof PromptLibraryIndexRoute
  '/partnerships/demo-requests': typeof PartnershipsLayoutDemoRequestsRoute
  '/partnerships/institution-partners': typeof PartnershipsLayoutInstitutionPartnersRoute
  '/partnerships/mentors': typeof PartnershipsLayoutMentorsRoute
  '/partnerships/': typeof PartnershipsLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/become-a-mentor': typeof BecomeAMentorRoute
  '/become-a-partner-institution': typeof BecomeAPartnerInstitutionRoute
  '/certificate': typeof CertificateRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/games': typeof GamesRoute
  '/internships': typeof InternshipsRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/onboarding': typeof OnboardingRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tests': typeof TestsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/assessment-questions': typeof AdminAssessmentQuestionsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/community/institutions': typeof CommunityInstitutionsRoute
  '/community/mentors': typeof CommunityMentorsRoute
  '/partnerships/login': typeof PartnershipsLoginRoute
  '/prompt-library/$libraryId': typeof PromptLibraryLibraryIdRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/community': typeof CommunityIndexRoute
  '/prompt-library': typeof PromptLibraryIndexRoute
  '/partnerships/demo-requests': typeof PartnershipsLayoutDemoRequestsRoute
  '/partnerships/institution-partners': typeof PartnershipsLayoutInstitutionPartnersRoute
  '/partnerships/mentors': typeof PartnershipsLayoutMentorsRoute
  '/partnerships': typeof PartnershipsLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/become-a-mentor': typeof BecomeAMentorRoute
  '/become-a-partner-institution': typeof BecomeAPartnerInstitutionRoute
  '/certificate': typeof CertificateRoute
  '/community': typeof CommunityRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/games': typeof GamesRoute
  '/internships': typeof InternshipsRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/onboarding': typeof OnboardingRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tests': typeof TestsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/assessment-questions': typeof AdminAssessmentQuestionsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/community/institutions': typeof CommunityInstitutionsRoute
  '/community/mentors': typeof CommunityMentorsRoute
  '/partnerships/_layout': typeof PartnershipsLayoutRouteWithChildren
  '/partnerships/login': typeof PartnershipsLoginRoute
  '/prompt-library/$libraryId': typeof PromptLibraryLibraryIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/prompt-library/': typeof PromptLibraryIndexRoute
  '/partnerships/_layout/demo-requests': typeof PartnershipsLayoutDemoRequestsRoute
  '/partnerships/_layout/institution-partners': typeof PartnershipsLayoutInstitutionPartnersRoute
  '/partnerships/_layout/mentors': typeof PartnershipsLayoutMentorsRoute
  '/partnerships/_layout/': typeof PartnershipsLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assessment'
    | '/become-a-mentor'
    | '/become-a-partner-institution'
    | '/certificate'
    | '/community'
    | '/dashboard'
    | '/feedback'
    | '/forgot-password'
    | '/games'
    | '/internships'
    | '/learning'
    | '/login'
    | '/mentor'
    | '/onboarding'
    | '/practice'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/resources'
    | '/signup'
    | '/support'
    | '/terms'
    | '/tests'
    | '/admin/ads'
    | '/admin/assessment-questions'
    | '/admin/blog'
    | '/admin/certificates'
    | '/admin/feedback'
    | '/admin/users'
    | '/blog/$slug'
    | '/community/institutions'
    | '/community/mentors'
    | '/partnerships'
    | '/partnerships/login'
    | '/prompt-library/$libraryId'
    | '/admin/'
    | '/blog/'
    | '/community/'
    | '/prompt-library/'
    | '/partnerships/demo-requests'
    | '/partnerships/institution-partners'
    | '/partnerships/mentors'
    | '/partnerships/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/become-a-mentor'
    | '/become-a-partner-institution'
    | '/certificate'
    | '/dashboard'
    | '/feedback'
    | '/forgot-password'
    | '/games'
    | '/internships'
    | '/learning'
    | '/login'
    | '/mentor'
    | '/onboarding'
    | '/practice'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/resources'
    | '/signup'
    | '/support'
    | '/terms'
    | '/tests'
    | '/admin/ads'
    | '/admin/assessment-questions'
    | '/admin/blog'
    | '/admin/certificates'
    | '/admin/feedback'
    | '/admin/users'
    | '/blog/$slug'
    | '/community/institutions'
    | '/community/mentors'
    | '/partnerships/login'
    | '/prompt-library/$libraryId'
    | '/admin'
    | '/blog'
    | '/community'
    | '/prompt-library'
    | '/partnerships/demo-requests'
    | '/partnerships/institution-partners'
    | '/partnerships/mentors'
    | '/partnerships'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assessment'
    | '/become-a-mentor'
    | '/become-a-partner-institution'
    | '/certificate'
    | '/community'
    | '/dashboard'
    | '/feedback'
    | '/forgot-password'
    | '/games'
    | '/internships'
    | '/learning'
    | '/login'
    | '/mentor'
    | '/onboarding'
    | '/practice'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/resources'
    | '/signup'
    | '/support'
    | '/terms'
    | '/tests'
    | '/admin/ads'
    | '/admin/assessment-questions'
    | '/admin/blog'
    | '/admin/certificates'
    | '/admin/feedback'
    | '/admin/users'
    | '/blog/$slug'
    | '/community/institutions'
    | '/community/mentors'
    | '/partnerships/_layout'
    | '/partnerships/login'
    | '/prompt-library/$libraryId'
    | '/admin/'
    | '/blog/'
    | '/community/'
    | '/prompt-library/'
    | '/partnerships/_layout/demo-requests'
    | '/partnerships/_layout/institution-partners'
    | '/partnerships/_layout/mentors'
    | '/partnerships/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssessmentRoute: typeof AssessmentRoute
  BecomeAMentorRoute: typeof BecomeAMentorRoute
  BecomeAPartnerInstitutionRoute: typeof BecomeAPartnerInstitutionRoute
  CertificateRoute: typeof CertificateRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FeedbackRoute: typeof FeedbackRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GamesRoute: typeof GamesRoute
  InternshipsRoute: typeof InternshipsRoute
  LearningRoute: typeof LearningRoute
  LoginRoute: typeof LoginRoute
  MentorRoute: typeof MentorRoute
  OnboardingRoute: typeof OnboardingRoute
  PracticeRoute: typeof PracticeRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TestsRoute: typeof TestsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PartnershipsLayoutRoute: typeof PartnershipsLayoutRouteWithChildren
  PartnershipsLoginRoute: typeof PartnershipsLoginRoute
  PromptLibraryLibraryIdRoute: typeof PromptLibraryLibraryIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PromptLibraryIndexRoute: typeof PromptLibraryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-partner-institution': {
      id: '/become-a-partner-institution'
      path: '/become-a-partner-institution'
      fullPath: '/become-a-partner-institution'
      preLoaderRoute: typeof BecomeAPartnerInstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-mentor': {
      id: '/become-a-mentor'
      path: '/become-a-mentor'
      fullPath: '/become-a-mentor'
      preLoaderRoute: typeof BecomeAMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-library/': {
      id: '/prompt-library/'
      path: '/prompt-library'
      fullPath: '/prompt-library/'
      preLoaderRoute: typeof PromptLibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/prompt-library/$libraryId': {
      id: '/prompt-library/$libraryId'
      path: '/prompt-library/$libraryId'
      fullPath: '/prompt-library/$libraryId'
      preLoaderRoute: typeof PromptLibraryLibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships/login': {
      id: '/partnerships/login'
      path: '/partnerships/login'
      fullPath: '/partnerships/login'
      preLoaderRoute: typeof PartnershipsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships/_layout': {
      id: '/partnerships/_layout'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/mentors': {
      id: '/community/mentors'
      path: '/mentors'
      fullPath: '/community/mentors'
      preLoaderRoute: typeof CommunityMentorsRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/institutions': {
      id: '/community/institutions'
      path: '/institutions'
      fullPath: '/community/institutions'
      preLoaderRoute: typeof CommunityInstitutionsRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assessment-questions': {
      id: '/admin/assessment-questions'
      path: '/assessment-questions'
      fullPath: '/admin/assessment-questions'
      preLoaderRoute: typeof AdminAssessmentQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/partnerships/_layout/': {
      id: '/partnerships/_layout/'
      path: '/'
      fullPath: '/partnerships/'
      preLoaderRoute: typeof PartnershipsLayoutIndexRouteImport
      parentRoute: typeof PartnershipsLayoutRoute
    }
    '/partnerships/_layout/mentors': {
      id: '/partnerships/_layout/mentors'
      path: '/mentors'
      fullPath: '/partnerships/mentors'
      preLoaderRoute: typeof PartnershipsLayoutMentorsRouteImport
      parentRoute: typeof PartnershipsLayoutRoute
    }
    '/partnerships/_layout/institution-partners': {
      id: '/partnerships/_layout/institution-partners'
      path: '/institution-partners'
      fullPath: '/partnerships/institution-partners'
      preLoaderRoute: typeof PartnershipsLayoutInstitutionPartnersRouteImport
      parentRoute: typeof PartnershipsLayoutRoute
    }
    '/partnerships/_layout/demo-requests': {
      id: '/partnerships/_layout/demo-requests'
      path: '/demo-requests'
      fullPath: '/partnerships/demo-requests'
      preLoaderRoute: typeof PartnershipsLayoutDemoRequestsRouteImport
      parentRoute: typeof PartnershipsLayoutRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAssessmentQuestionsRoute: typeof AdminAssessmentQuestionsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminAssessmentQuestionsRoute: AdminAssessmentQuestionsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CommunityRouteChildren {
  CommunityInstitutionsRoute: typeof CommunityInstitutionsRoute
  CommunityMentorsRoute: typeof CommunityMentorsRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityInstitutionsRoute: CommunityInstitutionsRoute,
  CommunityMentorsRoute: CommunityMentorsRoute,
  CommunityIndexRoute: CommunityIndexRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface PartnershipsLayoutRouteChildren {
  PartnershipsLayoutDemoRequestsRoute: typeof PartnershipsLayoutDemoRequestsRoute
  PartnershipsLayoutInstitutionPartnersRoute: typeof PartnershipsLayoutInstitutionPartnersRoute
  PartnershipsLayoutMentorsRoute: typeof PartnershipsLayoutMentorsRoute
  PartnershipsLayoutIndexRoute: typeof PartnershipsLayoutIndexRoute
}

const PartnershipsLayoutRouteChildren: PartnershipsLayoutRouteChildren = {
  PartnershipsLayoutDemoRequestsRoute: PartnershipsLayoutDemoRequestsRoute,
  PartnershipsLayoutInstitutionPartnersRoute:
    PartnershipsLayoutInstitutionPartnersRoute,
  PartnershipsLayoutMentorsRoute: PartnershipsLayoutMentorsRoute,
  PartnershipsLayoutIndexRoute: PartnershipsLayoutIndexRoute,
}

const PartnershipsLayoutRouteWithChildren =
  PartnershipsLayoutRoute._addFileChildren(PartnershipsLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AssessmentRoute: AssessmentRoute,
  BecomeAMentorRoute: BecomeAMentorRoute,
  BecomeAPartnerInstitutionRoute: BecomeAPartnerInstitutionRoute,
  CertificateRoute: CertificateRoute,
  CommunityRoute: CommunityRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FeedbackRoute: FeedbackRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GamesRoute: GamesRoute,
  InternshipsRoute: InternshipsRoute,
  LearningRoute: LearningRoute,
  LoginRoute: LoginRoute,
  MentorRoute: MentorRoute,
  OnboardingRoute: OnboardingRoute,
  PracticeRoute: PracticeRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TestsRoute: TestsRoute,
  BlogSlugRoute: BlogSlugRoute,
  PartnershipsLayoutRoute: PartnershipsLayoutRouteWithChildren,
  PartnershipsLoginRoute: PartnershipsLoginRoute,
  PromptLibraryLibraryIdRoute: PromptLibraryLibraryIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  PromptLibraryIndexRoute: PromptLibraryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
