/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WellnessRouteImport } from './routes/wellness'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DigitalMarketingRouteImport } from './routes/digital-marketing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as CareerReadinessWaitlistRouteImport } from './routes/career-readiness-waitlist'
import { Route as CareerReadinessAssessmentRouteImport } from './routes/career-readiness-assessment'
import { Route as CareerReadinessRouteImport } from './routes/career-readiness'
import { Route as BecomeAnInternshipPartnerRouteImport } from './routes/become-an-internship-partner'
import { Route as BecomeAPartnerInstitutionRouteImport } from './routes/become-a-partner-institution'
import { Route as BecomeAMentorRouteImport } from './routes/become-a-mentor'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AptitudeAssessmentRouteImport } from './routes/aptitude-assessment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as PartnershipsLoginRouteImport } from './routes/partnerships/login'
import { Route as CommunityMentorsRouteImport } from './routes/community/mentors'
import { Route as CommunityInstitutionsRouteImport } from './routes/community/institutions'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as AdminLayoutWellnessRouteImport } from './routes/admin/_layout/wellness'
import { Route as AdminLayoutVerificationRouteImport } from './routes/admin/_layout/verification'
import { Route as AdminLayoutUsersRouteImport } from './routes/admin/_layout/users'
import { Route as AdminLayoutMentorsRouteImport } from './routes/admin/_layout/mentors'
import { Route as AdminLayoutMentorReviewsRouteImport } from './routes/admin/_layout/mentor-reviews'
import { Route as AdminLayoutInstitutionPartnersRouteImport } from './routes/admin/_layout/institution-partners'
import { Route as AdminLayoutFeedbackRouteImport } from './routes/admin/_layout/feedback'
import { Route as AdminLayoutDemoRequestsRouteImport } from './routes/admin/_layout/demo-requests'
import { Route as AdminLayoutCertificatesRouteImport } from './routes/admin/_layout/certificates'
import { Route as AdminLayoutBlogRouteImport } from './routes/admin/_layout/blog'
import { Route as AdminLayoutAssessmentQuestionsRouteImport } from './routes/admin/_layout/assessment-questions'
import { Route as AdminLayoutAdsRouteImport } from './routes/admin/_layout/ads'

const WellnessRoute = WellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalMarketingRoute = DigitalMarketingRouteImport.update({
  id: '/digital-marketing',
  path: '/digital-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerReadinessWaitlistRoute = CareerReadinessWaitlistRouteImport.update({
  id: '/career-readiness-waitlist',
  path: '/career-readiness-waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerReadinessAssessmentRoute =
  CareerReadinessAssessmentRouteImport.update({
    id: '/career-readiness-assessment',
    path: '/career-readiness-assessment',
    getParentRoute: () => rootRouteImport,
  } as any)
const CareerReadinessRoute = CareerReadinessRouteImport.update({
  id: '/career-readiness',
  path: '/career-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAnInternshipPartnerRoute =
  BecomeAnInternshipPartnerRouteImport.update({
    id: '/become-an-internship-partner',
    path: '/become-an-internship-partner',
    getParentRoute: () => rootRouteImport,
  } as any)
const BecomeAPartnerInstitutionRoute =
  BecomeAPartnerInstitutionRouteImport.update({
    id: '/become-a-partner-institution',
    path: '/become-a-partner-institution',
    getParentRoute: () => rootRouteImport,
  } as any)
const BecomeAMentorRoute = BecomeAMentorRouteImport.update({
  id: '/become-a-mentor',
  path: '/become-a-mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AptitudeAssessmentRoute = AptitudeAssessmentRouteImport.update({
  id: '/aptitude-assessment',
  path: '/aptitude-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsLoginRoute = PartnershipsLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PartnershipsRoute,
} as any)
const CommunityMentorsRoute = CommunityMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityInstitutionsRoute = CommunityInstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => CommunityRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutWellnessRoute = AdminLayoutWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutVerificationRoute = AdminLayoutVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutUsersRoute = AdminLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutMentorsRoute = AdminLayoutMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutMentorReviewsRoute =
  AdminLayoutMentorReviewsRouteImport.update({
    id: '/mentor-reviews',
    path: '/mentor-reviews',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutInstitutionPartnersRoute =
  AdminLayoutInstitutionPartnersRouteImport.update({
    id: '/institution-partners',
    path: '/institution-partners',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutFeedbackRoute = AdminLayoutFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutDemoRequestsRoute = AdminLayoutDemoRequestsRouteImport.update({
  id: '/demo-requests',
  path: '/demo-requests',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutCertificatesRoute = AdminLayoutCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutBlogRoute = AdminLayoutBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutAssessmentQuestionsRoute =
  AdminLayoutAssessmentQuestionsRouteImport.update({
    id: '/assessment-questions',
    path: '/assessment-questions',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAdsRoute = AdminLayoutAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aptitude-assessment': typeof AptitudeAssessmentRoute
  '/assessment': typeof AssessmentRoute
  '/become-a-mentor': typeof BecomeAMentorRoute
  '/become-a-partner-institution': typeof BecomeAPartnerInstitutionRoute
  '/become-an-internship-partner': typeof BecomeAnInternshipPartnerRoute
  '/career-readiness': typeof CareerReadinessRoute
  '/career-readiness-assessment': typeof CareerReadinessAssessmentRoute
  '/career-readiness-waitlist': typeof CareerReadinessWaitlistRoute
  '/certificate': typeof CertificateRoute
  '/community': typeof CommunityRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/games': typeof GamesRoute
  '/internships': typeof InternshipsRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/onboarding': typeof OnboardingRoute
  '/partnerships': typeof PartnershipsRouteWithChildren
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tests': typeof TestsRoute
  '/wellness': typeof WellnessRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/community/institutions': typeof CommunityInstitutionsRoute
  '/community/mentors': typeof CommunityMentorsRoute
  '/partnerships/login': typeof PartnershipsLoginRoute
  '/blog/': typeof BlogIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/admin/ads': typeof AdminLayoutAdsRoute
  '/admin/assessment-questions': typeof AdminLayoutAssessmentQuestionsRoute
  '/admin/blog': typeof AdminLayoutBlogRoute
  '/admin/certificates': typeof AdminLayoutCertificatesRoute
  '/admin/demo-requests': typeof AdminLayoutDemoRequestsRoute
  '/admin/feedback': typeof AdminLayoutFeedbackRoute
  '/admin/institution-partners': typeof AdminLayoutInstitutionPartnersRoute
  '/admin/mentor-reviews': typeof AdminLayoutMentorReviewsRoute
  '/admin/mentors': typeof AdminLayoutMentorsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/admin/verification': typeof AdminLayoutVerificationRoute
  '/admin/wellness': typeof AdminLayoutWellnessRoute
  '/admin/': typeof AdminLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aptitude-assessment': typeof AptitudeAssessmentRoute
  '/assessment': typeof AssessmentRoute
  '/become-a-mentor': typeof BecomeAMentorRoute
  '/become-a-partner-institution': typeof BecomeAPartnerInstitutionRoute
  '/become-an-internship-partner': typeof BecomeAnInternshipPartnerRoute
  '/career-readiness': typeof CareerReadinessRoute
  '/career-readiness-assessment': typeof CareerReadinessAssessmentRoute
  '/career-readiness-waitlist': typeof CareerReadinessWaitlistRoute
  '/certificate': typeof CertificateRoute
  '/dashboard': typeof DashboardRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/games': typeof GamesRoute
  '/internships': typeof InternshipsRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/onboarding': typeof OnboardingRoute
  '/partnerships': typeof PartnershipsRouteWithChildren
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tests': typeof TestsRoute
  '/wellness': typeof WellnessRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/community/institutions': typeof CommunityInstitutionsRoute
  '/community/mentors': typeof CommunityMentorsRoute
  '/partnerships/login': typeof PartnershipsLoginRoute
  '/blog': typeof BlogIndexRoute
  '/community': typeof CommunityIndexRoute
  '/admin/ads': typeof AdminLayoutAdsRoute
  '/admin/assessment-questions': typeof AdminLayoutAssessmentQuestionsRoute
  '/admin/blog': typeof AdminLayoutBlogRoute
  '/admin/certificates': typeof AdminLayoutCertificatesRoute
  '/admin/demo-requests': typeof AdminLayoutDemoRequestsRoute
  '/admin/feedback': typeof AdminLayoutFeedbackRoute
  '/admin/institution-partners': typeof AdminLayoutInstitutionPartnersRoute
  '/admin/mentor-reviews': typeof AdminLayoutMentorReviewsRoute
  '/admin/mentors': typeof AdminLayoutMentorsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/admin/verification': typeof AdminLayoutVerificationRoute
  '/admin/wellness': typeof AdminLayoutWellnessRoute
  '/admin': typeof AdminLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aptitude-assessment': typeof AptitudeAssessmentRoute
  '/assessment': typeof AssessmentRoute
  '/become-a-mentor': typeof BecomeAMentorRoute
  '/become-a-partner-institution': typeof BecomeAPartnerInstitutionRoute
  '/become-an-internship-partner': typeof BecomeAnInternshipPartnerRoute
  '/career-readiness': typeof CareerReadinessRoute
  '/career-readiness-assessment': typeof CareerReadinessAssessmentRoute
  '/career-readiness-waitlist': typeof CareerReadinessWaitlistRoute
  '/certificate': typeof CertificateRoute
  '/community': typeof CommunityRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/games': typeof GamesRoute
  '/internships': typeof InternshipsRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/onboarding': typeof OnboardingRoute
  '/partnerships': typeof PartnershipsRouteWithChildren
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tests': typeof TestsRoute
  '/wellness': typeof WellnessRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/community/institutions': typeof CommunityInstitutionsRoute
  '/community/mentors': typeof CommunityMentorsRoute
  '/partnerships/login': typeof PartnershipsLoginRoute
  '/blog/': typeof BlogIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/admin/_layout/ads': typeof AdminLayoutAdsRoute
  '/admin/_layout/assessment-questions': typeof AdminLayoutAssessmentQuestionsRoute
  '/admin/_layout/blog': typeof AdminLayoutBlogRoute
  '/admin/_layout/certificates': typeof AdminLayoutCertificatesRoute
  '/admin/_layout/demo-requests': typeof AdminLayoutDemoRequestsRoute
  '/admin/_layout/feedback': typeof AdminLayoutFeedbackRoute
  '/admin/_layout/institution-partners': typeof AdminLayoutInstitutionPartnersRoute
  '/admin/_layout/mentor-reviews': typeof AdminLayoutMentorReviewsRoute
  '/admin/_layout/mentors': typeof AdminLayoutMentorsRoute
  '/admin/_layout/users': typeof AdminLayoutUsersRoute
  '/admin/_layout/verification': typeof AdminLayoutVerificationRoute
  '/admin/_layout/wellness': typeof AdminLayoutWellnessRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aptitude-assessment'
    | '/assessment'
    | '/become-a-mentor'
    | '/become-a-partner-institution'
    | '/become-an-internship-partner'
    | '/career-readiness'
    | '/career-readiness-assessment'
    | '/career-readiness-waitlist'
    | '/certificate'
    | '/community'
    | '/dashboard'
    | '/digital-marketing'
    | '/feedback'
    | '/forgot-password'
    | '/games'
    | '/internships'
    | '/learning'
    | '/login'
    | '/mentor'
    | '/onboarding'
    | '/partnerships'
    | '/practice'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/resources'
    | '/signup'
    | '/support'
    | '/terms'
    | '/tests'
    | '/wellness'
    | '/admin'
    | '/admin/login'
    | '/blog/$slug'
    | '/community/institutions'
    | '/community/mentors'
    | '/partnerships/login'
    | '/blog/'
    | '/community/'
    | '/admin/ads'
    | '/admin/assessment-questions'
    | '/admin/blog'
    | '/admin/certificates'
    | '/admin/demo-requests'
    | '/admin/feedback'
    | '/admin/institution-partners'
    | '/admin/mentor-reviews'
    | '/admin/mentors'
    | '/admin/users'
    | '/admin/verification'
    | '/admin/wellness'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aptitude-assessment'
    | '/assessment'
    | '/become-a-mentor'
    | '/become-a-partner-institution'
    | '/become-an-internship-partner'
    | '/career-readiness'
    | '/career-readiness-assessment'
    | '/career-readiness-waitlist'
    | '/certificate'
    | '/dashboard'
    | '/digital-marketing'
    | '/feedback'
    | '/forgot-password'
    | '/games'
    | '/internships'
    | '/learning'
    | '/login'
    | '/mentor'
    | '/onboarding'
    | '/partnerships'
    | '/practice'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/resources'
    | '/signup'
    | '/support'
    | '/terms'
    | '/tests'
    | '/wellness'
    | '/admin/login'
    | '/blog/$slug'
    | '/community/institutions'
    | '/community/mentors'
    | '/partnerships/login'
    | '/blog'
    | '/community'
    | '/admin/ads'
    | '/admin/assessment-questions'
    | '/admin/blog'
    | '/admin/certificates'
    | '/admin/demo-requests'
    | '/admin/feedback'
    | '/admin/institution-partners'
    | '/admin/mentor-reviews'
    | '/admin/mentors'
    | '/admin/users'
    | '/admin/verification'
    | '/admin/wellness'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/aptitude-assessment'
    | '/assessment'
    | '/become-a-mentor'
    | '/become-a-partner-institution'
    | '/become-an-internship-partner'
    | '/career-readiness'
    | '/career-readiness-assessment'
    | '/career-readiness-waitlist'
    | '/certificate'
    | '/community'
    | '/dashboard'
    | '/digital-marketing'
    | '/feedback'
    | '/forgot-password'
    | '/games'
    | '/internships'
    | '/learning'
    | '/login'
    | '/mentor'
    | '/onboarding'
    | '/partnerships'
    | '/practice'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/resources'
    | '/signup'
    | '/support'
    | '/terms'
    | '/tests'
    | '/wellness'
    | '/admin/_layout'
    | '/admin/login'
    | '/blog/$slug'
    | '/community/institutions'
    | '/community/mentors'
    | '/partnerships/login'
    | '/blog/'
    | '/community/'
    | '/admin/_layout/ads'
    | '/admin/_layout/assessment-questions'
    | '/admin/_layout/blog'
    | '/admin/_layout/certificates'
    | '/admin/_layout/demo-requests'
    | '/admin/_layout/feedback'
    | '/admin/_layout/institution-partners'
    | '/admin/_layout/mentor-reviews'
    | '/admin/_layout/mentors'
    | '/admin/_layout/users'
    | '/admin/_layout/verification'
    | '/admin/_layout/wellness'
    | '/admin/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AptitudeAssessmentRoute: typeof AptitudeAssessmentRoute
  AssessmentRoute: typeof AssessmentRoute
  BecomeAMentorRoute: typeof BecomeAMentorRoute
  BecomeAPartnerInstitutionRoute: typeof BecomeAPartnerInstitutionRoute
  BecomeAnInternshipPartnerRoute: typeof BecomeAnInternshipPartnerRoute
  CareerReadinessRoute: typeof CareerReadinessRoute
  CareerReadinessAssessmentRoute: typeof CareerReadinessAssessmentRoute
  CareerReadinessWaitlistRoute: typeof CareerReadinessWaitlistRoute
  CertificateRoute: typeof CertificateRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DigitalMarketingRoute: typeof DigitalMarketingRoute
  FeedbackRoute: typeof FeedbackRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GamesRoute: typeof GamesRoute
  InternshipsRoute: typeof InternshipsRoute
  LearningRoute: typeof LearningRoute
  LoginRoute: typeof LoginRoute
  MentorRoute: typeof MentorRoute
  OnboardingRoute: typeof OnboardingRoute
  PartnershipsRoute: typeof PartnershipsRouteWithChildren
  PracticeRoute: typeof PracticeRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TestsRoute: typeof TestsRoute
  WellnessRoute: typeof WellnessRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wellness': {
      id: '/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof WellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-marketing': {
      id: '/digital-marketing'
      path: '/digital-marketing'
      fullPath: '/digital-marketing'
      preLoaderRoute: typeof DigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-readiness-waitlist': {
      id: '/career-readiness-waitlist'
      path: '/career-readiness-waitlist'
      fullPath: '/career-readiness-waitlist'
      preLoaderRoute: typeof CareerReadinessWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-readiness-assessment': {
      id: '/career-readiness-assessment'
      path: '/career-readiness-assessment'
      fullPath: '/career-readiness-assessment'
      preLoaderRoute: typeof CareerReadinessAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-readiness': {
      id: '/career-readiness'
      path: '/career-readiness'
      fullPath: '/career-readiness'
      preLoaderRoute: typeof CareerReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-an-internship-partner': {
      id: '/become-an-internship-partner'
      path: '/become-an-internship-partner'
      fullPath: '/become-an-internship-partner'
      preLoaderRoute: typeof BecomeAnInternshipPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-partner-institution': {
      id: '/become-a-partner-institution'
      path: '/become-a-partner-institution'
      fullPath: '/become-a-partner-institution'
      preLoaderRoute: typeof BecomeAPartnerInstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-mentor': {
      id: '/become-a-mentor'
      path: '/become-a-mentor'
      fullPath: '/become-a-mentor'
      preLoaderRoute: typeof BecomeAMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aptitude-assessment': {
      id: '/aptitude-assessment'
      path: '/aptitude-assessment'
      fullPath: '/aptitude-assessment'
      preLoaderRoute: typeof AptitudeAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships/login': {
      id: '/partnerships/login'
      path: '/login'
      fullPath: '/partnerships/login'
      preLoaderRoute: typeof PartnershipsLoginRouteImport
      parentRoute: typeof PartnershipsRoute
    }
    '/community/mentors': {
      id: '/community/mentors'
      path: '/mentors'
      fullPath: '/community/mentors'
      preLoaderRoute: typeof CommunityMentorsRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/institutions': {
      id: '/community/institutions'
      path: '/institutions'
      fullPath: '/community/institutions'
      preLoaderRoute: typeof CommunityInstitutionsRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/wellness': {
      id: '/admin/_layout/wellness'
      path: '/wellness'
      fullPath: '/admin/wellness'
      preLoaderRoute: typeof AdminLayoutWellnessRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/verification': {
      id: '/admin/_layout/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminLayoutVerificationRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/users': {
      id: '/admin/_layout/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminLayoutUsersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/mentors': {
      id: '/admin/_layout/mentors'
      path: '/mentors'
      fullPath: '/admin/mentors'
      preLoaderRoute: typeof AdminLayoutMentorsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/mentor-reviews': {
      id: '/admin/_layout/mentor-reviews'
      path: '/mentor-reviews'
      fullPath: '/admin/mentor-reviews'
      preLoaderRoute: typeof AdminLayoutMentorReviewsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/institution-partners': {
      id: '/admin/_layout/institution-partners'
      path: '/institution-partners'
      fullPath: '/admin/institution-partners'
      preLoaderRoute: typeof AdminLayoutInstitutionPartnersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/feedback': {
      id: '/admin/_layout/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminLayoutFeedbackRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/demo-requests': {
      id: '/admin/_layout/demo-requests'
      path: '/demo-requests'
      fullPath: '/admin/demo-requests'
      preLoaderRoute: typeof AdminLayoutDemoRequestsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/certificates': {
      id: '/admin/_layout/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminLayoutCertificatesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/blog': {
      id: '/admin/_layout/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminLayoutBlogRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/assessment-questions': {
      id: '/admin/_layout/assessment-questions'
      path: '/assessment-questions'
      fullPath: '/admin/assessment-questions'
      preLoaderRoute: typeof AdminLayoutAssessmentQuestionsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/ads': {
      id: '/admin/_layout/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminLayoutAdsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface CommunityRouteChildren {
  CommunityInstitutionsRoute: typeof CommunityInstitutionsRoute
  CommunityMentorsRoute: typeof CommunityMentorsRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityInstitutionsRoute: CommunityInstitutionsRoute,
  CommunityMentorsRoute: CommunityMentorsRoute,
  CommunityIndexRoute: CommunityIndexRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface PartnershipsRouteChildren {
  PartnershipsLoginRoute: typeof PartnershipsLoginRoute
}

const PartnershipsRouteChildren: PartnershipsRouteChildren = {
  PartnershipsLoginRoute: PartnershipsLoginRoute,
}

const PartnershipsRouteWithChildren = PartnershipsRoute._addFileChildren(
  PartnershipsRouteChildren,
)

interface AdminLayoutRouteChildren {
  AdminLayoutAdsRoute: typeof AdminLayoutAdsRoute
  AdminLayoutAssessmentQuestionsRoute: typeof AdminLayoutAssessmentQuestionsRoute
  AdminLayoutBlogRoute: typeof AdminLayoutBlogRoute
  AdminLayoutCertificatesRoute: typeof AdminLayoutCertificatesRoute
  AdminLayoutDemoRequestsRoute: typeof AdminLayoutDemoRequestsRoute
  AdminLayoutFeedbackRoute: typeof AdminLayoutFeedbackRoute
  AdminLayoutInstitutionPartnersRoute: typeof AdminLayoutInstitutionPartnersRoute
  AdminLayoutMentorReviewsRoute: typeof AdminLayoutMentorReviewsRoute
  AdminLayoutMentorsRoute: typeof AdminLayoutMentorsRoute
  AdminLayoutUsersRoute: typeof AdminLayoutUsersRoute
  AdminLayoutVerificationRoute: typeof AdminLayoutVerificationRoute
  AdminLayoutWellnessRoute: typeof AdminLayoutWellnessRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutAdsRoute: AdminLayoutAdsRoute,
  AdminLayoutAssessmentQuestionsRoute: AdminLayoutAssessmentQuestionsRoute,
  AdminLayoutBlogRoute: AdminLayoutBlogRoute,
  AdminLayoutCertificatesRoute: AdminLayoutCertificatesRoute,
  AdminLayoutDemoRequestsRoute: AdminLayoutDemoRequestsRoute,
  AdminLayoutFeedbackRoute: AdminLayoutFeedbackRoute,
  AdminLayoutInstitutionPartnersRoute: AdminLayoutInstitutionPartnersRoute,
  AdminLayoutMentorReviewsRoute: AdminLayoutMentorReviewsRoute,
  AdminLayoutMentorsRoute: AdminLayoutMentorsRoute,
  AdminLayoutUsersRoute: AdminLayoutUsersRoute,
  AdminLayoutVerificationRoute: AdminLayoutVerificationRoute,
  AdminLayoutWellnessRoute: AdminLayoutWellnessRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AptitudeAssessmentRoute: AptitudeAssessmentRoute,
  AssessmentRoute: AssessmentRoute,
  BecomeAMentorRoute: BecomeAMentorRoute,
  BecomeAPartnerInstitutionRoute: BecomeAPartnerInstitutionRoute,
  BecomeAnInternshipPartnerRoute: BecomeAnInternshipPartnerRoute,
  CareerReadinessRoute: CareerReadinessRoute,
  CareerReadinessAssessmentRoute: CareerReadinessAssessmentRoute,
  CareerReadinessWaitlistRoute: CareerReadinessWaitlistRoute,
  CertificateRoute: CertificateRoute,
  CommunityRoute: CommunityRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DigitalMarketingRoute: DigitalMarketingRoute,
  FeedbackRoute: FeedbackRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GamesRoute: GamesRoute,
  InternshipsRoute: InternshipsRoute,
  LearningRoute: LearningRoute,
  LoginRoute: LoginRoute,
  MentorRoute: MentorRoute,
  OnboardingRoute: OnboardingRoute,
  PartnershipsRoute: PartnershipsRouteWithChildren,
  PracticeRoute: PracticeRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TestsRoute: TestsRoute,
  WellnessRoute: WellnessRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
